### ISSUE TITLE
No colors when piping to less/redirecting output

### ISSUE THREAD

**Issue by seandilda** [minitest/minitest-rg#14]
It looks like the code will only run colors if the output is a tty.  Unfortunately, this means when I pipe to less to more easily see all my output, the colors are removed.  Likewise, I can't redirect output, then less it as colors are also removed.

Can we get an option to force colors?

**Comment by grosser** [comment]
make a PR with a --color option ... alternatively use script -q /dev/null
ruby test.rb to fake tty

**Comment by zenspider** [comment]
7 years, no response. Closing
